### ISSUE TITLE
Add option to run a pre-command

### ISSUE THREAD

**Issue by Paul-dH** [charles-001/backup-warden#2]
Hey,

Cool project! I'm hoping to implement your backup solution in our gitlab backup procedure, but this requires a pre-command to be run before the backup starts. Is there a way to add this or do you have a suggestion how to add this? 

There are four commands in total that should be run, a command to backup the config, one that creates the backup and then two commands to tar the both backup files.

Thanks in advance!

Regards, Paul

**Comment by charles-001** [comment]
Hi @Paul-dH! Thanks for your interest. Backup Warden is meant to handle the life cycle of your backups by deleting and preserving them based on a retention policy. From what I'm understanding, you're wanting it to actually run commands to backup? Backup Warden is meant to be used after a backup is complete if so :)
