### ISSUE TITLE
Please add option to specify timezone used to create backup file names

### ISSUE THREAD

**Issue by Dimagog** [charles-001/backup-warden#3]
My backup files are named using UTC datetime of the moment when they were created.
When I run this tool, it treats them as datetimes in my computer’s timezone, and as a result the retention rules are shifted.

Please add a way to specify timezone (or at least UTC) for backup files.

**Comment by charles-001** [comment]
Hi @Dimagog - I will look to add this feature in the next version. Thank you!

**Comment by charles-001** [comment]
I've added this to the `main` branch as `--utc`. Can you `git clone` it, run `poetry install`, then `poetry run backup-warden` with your normal parameters to test that it works as you expect?

**Comment by Dimagog** [comment]
Thank you very much for such a quick turnaround on both issues!
