### ISSUE TITLE
How can I specify "keep all backups for the last 2 hours"

### ISSUE THREAD

**Issue by Dimagog** [charles-001/backup-warden#4]
Imagine I have backups happening every 30 minutes. I'd like to be able to keep all of them for the last 2 hours, then 24 hourly backups, etc.

Can I specify this today?

**Comment by charles-001** [comment]
Hi @Dimagog - unfortunately, that isn't currently supported. I saw that as a rare case that wouldn't be needed, but atlas, here you are :) I can look to add that.

**Comment by charles-001** [comment]
Hi @Dimagog - looks like you're looking for a `minutely` option which currently isn't supported. I can look to add that. Essentially, in this case, you'd set `minutely` to  `4`, then `hourly` to `24`

**Comment by charles-001** [comment]
I've added this to the `main` branch. Can you `git clone` it, run `poetry install`, then `poetry run backup-warden` with your normal parameters to test that it works as you expect?
